# Let's try Numpy Arrays
In this notebook we will see many different ways in which a **numpy array** can be created

## Exercise 1 numpy import and an array creation
Given the lists:
`l1 = [0., 1., 2.]`
`l2 = [True, False]`
create the corresponding numpy arrays and print their types 

In [2]:
import numpy as np

l1 = [0.,1.,2.]
l2 = [True, False]

l1np = np.array(l1)
l2np = np.array(l2)

print(l1np)
print(l2np)

[0. 1. 2.]
[ True False]


## Exercise 2 creates a multidimensional array

First creates a multidimensional array from the given list of lists
`l1 = [[[0., 1., 2.],[3., 4., 5.]],[[6., 7., 8.],[9., 10., 11.]]]`

Then print the number of **rows** and **columns** of the arrays

In [10]:
l1 = [[[0., 1., 2.],[3., 4., 5.]],[[6., 7., 8.],[9., 10., 11.]]]
array = np.array(l1)

print(f"shape: {array.shape}")

numero_matrici = len(array)
numero_righe = len(array[0])
numero_colonne = len(array[0][0])

print("Numero di matrici:", numero_matrici)
print("Righe per matrice:", numero_righe)
print("Colonne per matrice:", numero_colonne)


shape: (2, 2, 3)
Numero di matrici: 2
Righe per matrice: 2
Colonne per matrice: 3


## Exercise 3 creates a ndarray with values without using lists
Create:
1) an ndarray 3 x 3 of $1$s
2) an ndarray 2 x 2 of $0$s
3) an ndarray 1 x 2 of $9$s
4) an ndarray of shape () with value 39
5) an ndarray of shape (2,5) with values randomly distributed between 0 and 1
6) an ndarray with 100 (equispaced) elements between 0 and 5

*note*: always print the ndarray to console to make sure you correctly created it

In [25]:
array1 = np.ones((3,3))
print(f"array1 =\n{array1}\n")

array2 = np.zeros((2,2))
print(f"array2 =\n{array2}\n")

array3 = np.full((1,2), 9)
print(f"array3 =\n{array3}\n")

array4 = np.array(39)
print(f"array4 = {array4}")
print(f"array4 shape = {array4.shape}\n")

array5 = np.random.random((2,3))
print(f"array5 =\n{array5}\n")

array6 = np.linspace(0,5,100)
print(f"array6 =\n{array6}")

array1 =
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

array2 =
[[0. 0.]
 [0. 0.]]

array3 =
[[9 9]]

array4 = 39
array4 shape = ()

array5 =
[[0.56054268 0.7535131  0.25677364]
 [0.38482522 0.23710164 0.75218323]]

array6 =
[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3