# Let's makes some Numpy Operations
In this notebook, we will make some operations with Numpy arrays. We will use the following functions:
- Universal functions
- Aggregation functions
- Sorting
- Broadcasting


## Exercise 1 Universal Functions
Given an ndarray x = [4, -1, 7, 9, 3, -5] compute the sigmoid function $ y = sigmoid(x)$ which maps numbers $(-\inf +\inf) \rightarrow (0,1)$

$$ sigmoid(x) = \frac{1}{1 + e^{-x}}$$

In [3]:
%pip install numpy
import numpy as np


Note: you may need to restart the kernel to use updated packages.


In [4]:

x = np.array([4,-1,7,9,3,-5])
y = 1 / (1 + np.exp(-x))

print(y)

[0.98201379 0.26894142 0.99908895 0.99987661 0.95257413 0.00669285]


## Exercise 2 Aggregation functions
Given an array
x = [
    [2, 3, -4,],
    [7, 5, 9]
]

Return the mean of the elements along the rows and the minimum element along the columns

In [ ]:
x = np.array([[2,3,-4], [7,5,9]])

print(x)
print(f"x.shape = {x.shape}")
print(f"dtype = {x.dtype}")

mean = x.mean(axis=-1)
print(f"mean = {mean}")

min = x.min(axis=0)
print(f"min = {min}")


[[ 2  3 -4]
 [ 7  5  9]]
x.shape = (2, 3)
dtype = int64
mean = [0.33333333 7.        ]
min = [ 2  3 -4]


## Exercise 3 Sorting
Given the same array as in Ex. 1, i.e., x = [4, -1, 7, 9, 3, -5], find the 3 highest values and the positions of the 2 lowest values

In [18]:
x = np.array([4, -1, 7, 9, 3, -5])

ordine = np.argsort(x)  # indici degli elementi ordinati dal più piccolo al più grande

print(f"ordine = {ordine}")

tre_piu_alti = x[ordine[-3:][::-1]]
posizioni_due_piu_bassi = ordine[:2]

print("Tre valori più alti:", tre_piu_alti)
print("Posizioni dei due valori più bassi:", posizioni_due_piu_bassi)

ordine = [5 1 4 0 2 3]
Tre valori più alti: [9 7 4]
Posizioni dei due valori più bassi: [5 1]


# Exercise 4 Broadcasting
Compute the product between the array x1 = [[0,1,2], [3,4,5]] and the array x2 = [1, 2]
Does it raise an error? How shall x2 be modified to make the operation possible?


In [27]:
x1 = np.array([[0,1,2], [3,4,5]])
print(f"x1 = {x1}")

x2 = np.array([1,2])
print(f"x2 = {x2}")

try:
    prod = x1 * x2
    print(f"prod = {prod}")
except ValueError as e:
    print(f"Errore: {e}")

x2_colonna = x2[:, np.newaxis]  # shape (2, 1)
print(f"x2_colonna = {x2_colonna}")
print(f"shape = {x2_colonna.shape}")

prod = x1 * x2_colonna
print(f"prod = {prod}")


x1 = [[0 1 2]
 [3 4 5]]
x2 = [1 2]
Errore: operands could not be broadcast together with shapes (2,3) (2,) 
x2_colonna = [[1]
 [2]]
shape = (2, 1)
prod = [[ 0  1  2]
 [ 6  8 10]]


## Exercise 5 Broadcasting in practice: centering the features
A dataset is often stored as a matrix with **one row per sample** and **one column per feature**. Given

data = [
    [1, 200],
    [3, 400],
    [5, 900]
]

subtract from every column its mean, so that each feature has mean 0, **without a loop**. Which shapes are involved, and which broadcasting rules apply? Check that the mean of each column of the result is 0.

In [35]:
data = np.array([[1, 200], [3, 400], [5, 900]])
print(f"data =\n{data}")
print(f"shape = {data.shape}")

means = data.mean(axis=0)
print(f"means = {means}")
print(f"shape = {means.shape}")

subtracted = data - means
print(f"subtracted =\n{subtracted}")
print(f"shape = {subtracted.shape}")

means_after = subtracted.mean(axis=0)
print(f"Media delle colonne dopo la sottrazione = {means_after}")

data =
[[  1 200]
 [  3 400]
 [  5 900]]
shape = (3, 2)
means = [  3. 500.]
shape = (2,)
subtracted =
[[  -2. -300.]
 [   0. -100.]
 [   2.  400.]]
shape = (3, 2)
Media delle colonne dopo la sottrazione = [0. 0.]
